title: '"><svg onload=alert(1)>'
tagline: A brand new course on Learning Lab
description: '"><svg onload=alert(1)>'
template:
  repo: '"greaterlesssvg-onloadalert(1)greater-template'
  name: '"greaterlesssvg-onloadalert(1)greater'
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
